name: "Deploy"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: build woah
        run: pnpm install && pnpm run build
      - name: save build output
        uses: actions/upload-artifact@v4
        with:
          name: build_output
          path: build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download build
        uses: actions/download-artifact@v4
        with:
          name: build_output
          path: build
      - name: deploy to vps
        env:
          SSH_RSA_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          echo "$SSH_RSA_KEY" > actions_rsa;
          chmod 600 actions_rsa;
          rsync -azv --chown=root:leaderboard_dev --chmod=D775,F664 --del -O -e "ssh -o StrictHostKeyChecking=no -i actions_rsa" ./build/* github_actions@${{ secrets.VPS_IP }}:/var/www/gofish_leaderboard
